Repository nextcloud/app_api, pull requests merged in 2024-12, with the labels that each got.

#461 fix(TaskProcessingService): Use correct field name
  lib/Service/ProvidersAI/TaskProcessingService.php
Labels: backport-request

#463 fix(TaskProcessingService): Custom task type i/o shapes were broken
  lib/Service/ProvidersAI/TaskProcessingService.php
Labels: backport-request

#473 fix(initial-state): correct defaultDaemonConfig initial state
  lib/Service/ExAppsPageService.php
Labels: backport-request

#478 fix(occ): correct `app_api:app:update` enabled state of ExApps, introduce helper options
  lib/Command/ExApp/Update.php
Labels: backport-request

#448 copy SSL certificates from NC instance to ExApp upon install/update action
  .github/workflows/tests-deploy.yml
  lib/DeployActions/DockerActions.php
Labels: enhancement

#480 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
